version: "3.9"
services:
  web:
    build:
      context: .
      args:
        JEKYLL_UID: ${USER_ID}
        JEKYLL_GID: ${GROUP_ID}
    ports:
      - "4000:4000"
    volumes:
      - .:/srv/jekyll
