#+title: Site Entrepreneur d’intérêt général

Site du programme Entrepreneur d'intérêt général en cours de
construction.

Le dépôt pour le site en ligne actuellement est [[https://github.com/entrepreneur-interet-general/blog-eig2][ici]].

Le site test est visible en ligne [[http://site.eig-forever.org/][ici]].

* Comment ajouter une entrée de blog ?

Ajouter un fichier en markdown =.md= dans le répertoire =_posts=.

Le nom du fichier doit commencer par la date à laquelle l’entrée de
blog doit être publiée.  Par exemple :

: 2018-02-27-bootcamp-comment-souder-un-collectif-de-talents.md

qui sera publié le 27 février 2018.

Le nom de fichier doit se terminer par =.md=.

Le contenu du fichier doit commencer par un en-tête de cette forme :

: ---
: layout: post
: author: Soizic Pénicaud, équipe EIG
: author_link: https://entrepreneur-interet-general.etalab.gouv.fr/
: twitter: soizicpenicaud
: description: "Un résumé de l’entrée de blog"
: ---

suivi d’un contenu rédigé en markdown.

Voici un [[https://openclassrooms.com/courses/redigez-en-markdown][tutoriel]] pour apprendre la syntaxe du markdown.

* Comment ajouter un défi ?

Pour ajouter un défi, vous devez modifier le fichier =defis.html= et
ajouter un fichier au format markdown =.md= dans le répertoire =_defis=
avec un en-tête de ce format :

: ---
: layout: defi
: titre: balisenav
: site: https://entrepreneur-interet-general.etalab.gouv.fr
: annees: 2018
: mission: Faire de belles cartes marines !
: administration: SHOM
: type: Datascience
: eigs:
:   - Arnaud
:   - Adrien
: images:
:   - /images/@stock/medium-work-1.jpg
:   - /images/@stock/medium-work-2.jpg
: ---

Les images proposées dans =defis.html= sont de taille =600x500= et celles
proposées dans chaque défi de taille =800x500=.

* Comment ajouter une personne ?

Pour ajouter une personne, vous devez modifier le fichier
=communaute.html= et ajouter un fichier au format markdown =.md= dans le
répertoire =_communaute= avec un en-tête de ce format :

: ---
: layout: personne
: twitter: compte_twitter
: github: compte_github
: nom: Toto
: website: https://site-personnel.org
: annees: 2018
: defi: EIG team
: profil: Tout !
: images:
:   - /images/toto1.jpg
:   - /images/toto2.jpg
: ---

Les images proposées dans =communaute.html= et dans le fichier de chaque
personne sont de taille =500x500=.


