#+title: Site Entrepreneur d’intérêt général

Site du programme Entrepreneur d'intérêt général.

* Comment tester en local ?

Vous devez avoir installé =jekyll= et =bundle= sur votre système :

: ~$ gem install jekyll bundler

Pour tester l'affichage du site sur http://localhost:4000/

: ~$ git clone https://github.com/entrepreneur-interet-general/site-eig.git
: ~$ cd site-eig/
: ~$ bundle install
: ~$ jekyll serve --config _config.yml,_config_dev.yml --incremental

* Comment ajouter une entrée de blog ?

Ajouter un fichier en markdown =.md= dans le répertoire =_posts=.

Le nom du fichier doit commencer par la date à laquelle l’entrée de
blog doit être publiée.  Par exemple :

: 2018-02-27-bootcamp-comment-souder-un-collectif-de-talents.md

qui sera publié le 27 février 2018.

Le nom de fichier doit se terminer par =.md=.

Le contenu du fichier doit commencer par un en-tête de cette forme :

: ---
: layout: post
: author: Soizic Pénicaud, équipe EIG
: author_link: https://entrepreneur-interet-general.etalab.gouv.fr/
: twitter: soizicpenicaud
: title: "Le titre de l'entrée de blog"
: description: "Un résumé de l’entrée de blog"
: ---

suivi d’un contenu rédigé en markdown.

Voici un [[https://openclassrooms.com/courses/redigez-en-markdown][tutoriel]] pour apprendre la syntaxe du markdown.

* Comment ajouter un défi ?

Pour ajouter un défi, vous devez modifier le fichier =_data/defis.yml= et
ajouter un fichier au format markdown =.md= dans le répertoire =_defis=.


* Comment ajouter une personne ?

Pour ajouter une personne, vous devez modifier le fichier
=_data/personnes.yml= et ajouter un fichier au format markdown =.md= dans le
répertoire =_communaute=.

Les images proposées dans =communaute.html= et dans le fichier de chaque
personne sont de taille =500x500=.

* Licence

© 2018 Direction interministérielle du numérique et du système
d'information et de communication de l'État

© 2018 Les contributeurs accessibles via l'historique du dépôt.

Les contenus accessibles dans ce dépôt sont placés sous Licence
Ouverte 2.0 -- voir le fichier =LO.md= dans ce répertoire.  Vous êtes
libre de réutiliser les contenus de ce dépôt sous les conditions
précisées dans cette licence.
