#+title: Site Entrepreneurs d’intérêt général

Site du programme Entrepreneur d'intérêt général.

* Comment tester en local ?

Vous devez avoir installé =jekyll= et =bundle= sur votre système :

: ~$ gem install jekyll bundler

Pour tester l'affichage du site sur http://localhost:4000/

: ~$ git clone https://github.com/entrepreneur-interet-general/site-eig.git
: ~$ cd site-eig/
: ~$ bundle install
: ~$ jekyll serve --config _config.yml,_config_dev.yml --incremental

* Comment ajouter une entrée de blog ?

Ajouter un fichier en markdown =.md= dans le répertoire =_posts=.

Le nom du fichier doit commencer par la date à laquelle l’entrée de
blog doit être publiée.  Par exemple :

: 2018-02-27-bootcamp-comment-souder-un-collectif-de-talents.md

qui sera publié le 27 février 2018.

Le nom de fichier doit se terminer par =.md=.

Le contenu du fichier doit commencer par un en-tête de cette forme :

: ---
: layout: post
: author: Soizic Pénicaud, équipe EIG
: author_link: https://entrepreneur-interet-general.etalab.gouv.fr/
: twitter: soizicpenicaud
: title: "Le titre de l'entrée de blog"
: description: "Un résumé de l’entrée de blog"
: ---

suivi d’un contenu rédigé en markdown.

Voici un [[https://openclassrooms.com/courses/redigez-en-markdown][tutoriel]] pour apprendre la syntaxe du markdown.

* Comment ajouter un défi ?

Pour ajouter un défi, vous devez modifier le fichier =_data/defis.yml= et
ajouter un fichier au format markdown =.md= dans le répertoire =_defis=.


* Comment ajouter une personne ?

Pour ajouter une personne, vous devez modifier le fichier
=_data/personnes.yml= et ajouter un fichier au format markdown =.md= dans le
répertoire =_communaute=.

Les images proposées dans =communaute.html= et dans le fichier de chaque
personne sont de taille =500x500=.

* Fonctionnement des tags

Les pages d'archives de tags se trouvent dans le dossier /tag
Elles utilisent le layout _layouts/tag-archive.html
De nouveaux tags peuvent être ajoutés manuellement en ajoutant simplment des fichiers .md dans ce dossier, ou en lançant le script python suivant (Ce script nécessite l'installation [[https://pypi.org/project/awesome-slugify/][awesome-slugify]]) :

: ~$ python tags-generator.py

* Traduction

Traduction des pages : Les pages traduites se situent dans le répertoire `/en`. Afin de traduire une page, il est nécessaire de modifier dans un premier temps sa version française, en y précisant un identifiant unique `lang-ref` en entête (Exemple pour communauté : `lang-ref: communaute`).  Il suffit ensuite de copier cette page en version française dans le dossier `/en`, et de procéder à la traduction de la page. Il est également possible de préciser un permalien différent pour cette langue (Exemple pour communauté : `permalink: /en/community.html`).

Traduction des articles : Le procédé est le même que pour les pages, sauf que les articles à traduire se trouvent dans le répertoire `/_posts`, et doivent être copiés dans `/en/_posts`.

Traduction des FAQ : 2 nouveaux fichiers ont été créés dans le dossier `/_data`, faq-administrastions-en.yml et faq-eig-en.yml. Ces 2 fichiers sont de simples copies des fichiers faq-administrastions.yml et faq-eig.yml, et la traduction se fait directement dans ces fichiers, qui seront automatiquement remontés sur les bonnes pages FAQ.

Traduction du menu : Un nouveau fichier `/_data/nav-en.yml` a été crée (il s'agit d'une copie de `/_data/nav.yml`), permettant de traduire le menu, et d'y préciser en dur si des éléments du menu anglais ne sont pas traduits, en y précisant comme lien l'url `en/unavailable`.

Traduction des éléments communs (Footer + Textes) : Les textes et liens du footer, ainsi que certains textes (comme par exemple les liens "Articles plus récents"), sont administrables dans un nouveau fichier `/_data/traductions.yml`. Ce fichier contient les traductions sous forme de 2 tableaux, permettant d'y préciser les traductions en anglais et français des éléments communs du site.

* Licence

© 2018 Direction interministérielle du numérique et du système
d'information et de communication de l'État

© 2018 Les contributeurs accessibles via l'historique du dépôt.

Les contenus accessibles dans ce dépôt sont placés sous Licence
Ouverte 2.0 -- voir le fichier =LICENSE.md= dans ce répertoire.  Vous êtes
libre de réutiliser les contenus de ce dépôt sous les conditions
précisées dans cette licence.
